Title=Door Opener Test
Setup=General.set
Setup=cycle.set
Setup=Plot lists.set
Setup=DoorOpener
Setup=Options.set
Setup=Chain.set
Setup=Rerun.set
Display=cycle1.dsp,Product Temps
Display=cycle2.dsp,Test Times
Display=cycle3.dsp,Cycle Summary
Display=dooropener.dsp,Door Opener
Command=cycle.cmd
PointHelp=Group Numbers: 1-Freezer 2-Cab 3-Ambient 5-Freezer Door 6-Cab Door 8-LeftTree 9-RightTree 10-Cab Aux 11-Ext Hum
