Title=Development Test
Enabled= 0, 1
Enabled= 1, 1
Enabled= 2, 1
Enabled= 3, 1
Setup=general.set
Setup=logger.set
Setup=tccaldb.set
Setup=Plot lists.set
Setup=Options.set
Setup=Chain.set
Setup=wide.set
Setup=Rerun.set
PointEdit=logger.pnt
Point=YOK.PNT
Display=logger1.dsp,Test Information
Command=logger.cmd
PointHelp=Group Numbers: 1-Freezer 2-Cab 3-Ambient
